# Generated by Django 5.1.6 on 2025-02-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=10)),
                ("zip", models.IntegerField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("web", models.URLField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
